version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - run: 
          name: "Hello World"
          command: echo "Hello World!"
      - run:
          name: "npm install"    
          command: yarn install
      - run:
          name: "npm run build"
          command: yarn build


