version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    branches:
        only:
          - master  
    steps:
      - run: 
          name: "Hello World"
          command: echo "Hello World!"
      - run: yarn install
      - run: yarn build


