version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    branches:
        only:
          - master  
    steps:
      - checkout
      - run: echo "Hello World!"
      - run: yarn install
      - run: yarn build


